databases:
  - name: a_library_db
    databaseName: a_library_db
    user: django_user
    region: singapore
    plan: starter
 


services:
  - type: web
    name: a_library
    env: python
    region: singapore
    plan: starter
    branch: master
    healthCheckPath: /
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: a_library_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
    autoDeploy: true