# Generated by Django 4.1.7 on 2023-03-11 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobplace', '0006_remove_historymodel_reservation_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='images',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
